version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:12"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "chore"
      - "github-actions"
    groups:
      github-actions:
        patterns:
          - "*"
